services:
  react-app:
    build:
      context: .
      dockerfile: ./react-app/Dockerfile
    ports:
       - "5173:5173"
    volumes:
      - ./react-app:/src
      - /src/node_modules
    networks:
      - react-network

  python-server:
    build:
      context: .
      dockerfile: ./python-server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-server:/app
    networks:
      - react-network

networks:
  react-network:
    driver: bridge


